# Generated by Django 5.1.5 on 2025-01-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_postingconfiguration_socialmediaaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
