# Generated by Django 5.1.5 on 2025-01-20 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_remove_post_is_published_remove_post_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmoderation',
            name='flagged_reason',
        ),
        migrations.AlterField(
            model_name='contentmoderation',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content_management.post'),
        ),
        migrations.AlterField(
            model_name='contentmoderation',
            name='reviewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contentmoderation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
