# Generated by Django 5.1.5 on 2025-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_alter_bulkupload_uploaded_at_alter_bulkupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
